# Generated by Django 2.1 on 2019-04-06 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OCR_app', '0002_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_model',
        ),
    ]
