# Generated by Django 2.1 on 2019-04-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCR_app', '0004_auto_20190406_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_model',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='user_model',
            name='password2',
            field=models.CharField(default='password', max_length=20),
            preserve_default=False,
        ),
    ]
