# Generated by Django 2.1 on 2019-04-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OCR_app', '0005_auto_20190409_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_model',
            old_name='password1',
            new_name='Confirm',
        ),
        migrations.RenameField(
            model_name='user_model',
            old_name='password2',
            new_name='password',
        ),
    ]
