# Generated by Django 2.1 on 2019-04-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OCR_app', '0006_auto_20190409_2257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
